version: 2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2

    steps:
      - checkout
      - run: bundle install
      - run: bundle exec bundler-audit check --update
      - run: bundle exec brakeman --no-pager -q -w2
      - run: bundle exec rake db:migrate
      - run: bundle exec rake spec
