default: &default
  adapter: pg
  encoding: unicode
  pool: 5

development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

test:
  <<: *default
  database: heroku-ruby-0124_test

production:
  url: <%= ENV['DATABASE_URL'] %>
#
# production:
#   <<: *default
#   database: heroku-ruby-0124_production
#   username: heroku-ruby-0124
#   password: <%= ENV['HEROKU-RUBY-0124_DATABASE_PASSWORD'] %>
